# Generated by Django 2.1.7 on 2019-03-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20190323_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
